App/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email


class ContactForm(FlaskForm):
    fullname = StringField('Name', validators=[DataRequired()])
    email = StringField('Eamil Id', validators=[DataRequired(), Email()])
    message = TextAreaField('Message', validators=[DataRequired()])
    send = SubmitField('Send')

App/users/__init__.py
from flask import Blueprint

user = Blueprint('users', __name__)

from App.users import routes

App/users/routes.py
from App import db
from App.users import user
from flask import render_template, redirect, url_for, request, abort, jsonify, flash
from App.models import Post, Tag, Category, PostImage, PostCategory, PostTag, AccountSetting, Subscriber
from App.users.forms import ContactForm
import json


#Home Page Route
@user.route('/')
def home():
    title = 'SacheFacts | Home'
    site = AccountSetting.query.get(1)
    if site is None:
        abort(500)
    latest = Post.query.filter_by(status=True).order_by(Post.created_at.desc()).limit(5)
    featured = Post.query.filter_by(featured=True, status=True).all()
    tags = Tag.query.all()
    categories = Category.query.all()
    posttags = PostTag.query.all()
    postcategories = PostCategory.query.all()
    return render_template('user/home.html', title=title, site=site, latest=latest, featured=featured, tags=tags, categories=categories, posttags=posttags, postcategories=postcategories)


#About Page Route
@user.route('/about')
def about():
    title = 'SacheFacts | AboutUs'
    site = AccountSetting.query.get(1)
    if site is None:
        abort(500)
    return render_template('user/about.html', title=title, site=site)


#Contact Page Route
@user.route('/contact', methods=['GET', 'POST'])
def contact():
    title = 'SacheFacts | Contact'
    site = AccountSetting.query.get(1)
    if site is None:
        abort(500)
    form = ContactForm()
    if request.method == 'POST' and form.validate_on_submit():
        print(request.form)
        flash('Message Successfully Sent!', 'contact')
        return redirect(url_for('users.contact'))
    return render_template('user/contact.html', title=title, site=site, form=form)


#Blogs Page Route
@user.route('/blogs')
def blogs():
    title = 'SacheFacts | Blog'
    site = AccountSetting.query.get(1)
    if site is None:
        abort(500)
    if request.args.get('page'):
        if int(request.args.get('page')) > 0:
            page = int(request.args.get('page'))
        else:
            abort(404)
    else:
        page=1
    per_page=5
    blogs = Post.query.filter_by(status=True).order_by(Post.created_at.desc()).paginate(page, per_page)
    featured = Post.query.filter_by(featured=True, status=True).all()
    tags = Tag.query.all()
    categories = Category.query.all()
    posttags = PostTag.query.all()
    postcategories = PostCategory.query.all()
    return render_template('user/blogs.html', title=title, site=site, blogs=blogs, featured=featured, tags=tags, categories=categories, posttags=posttags, postcategories=postcategories)


#Single Blog Page Route
@user.route('/blog/<slag>')
def singleblog(slag):
    title = f'SacheFacts | { slag }'
    site = AccountSetting.query.get(1)
    if site is None:
        abort(500)
    blog = Post.query.filter_by(slag=slag, status=True).first_or_404()
    tags = Tag.query.all()
    categories = Category.query.all()
    posttags = PostTag.query.all()
    postcategories = PostCategory.query.all()
    url=None
    if blog.youtube:
        youtube = blog.youtube.replace('watch?v=', 'embed/')
        youtube = youtube.split('/')
        url = f'{ youtube[0] }//{ youtube[2] }/{ youtube[3] }/{ youtube[4] }?autoplay=1&playlist={ youtube[4] }&loop=1'
    return render_template('user/blog.html', title=title, site=site, blog=blog, tags=tags, categories=categories, posttags=posttags, postcategories=postcategories, youtube=url)


#Subscribe Page Route
@user.route('/subscribe', methods=['POST'])
def subscribe():
    if request.form.get('email'):
        if Subscriber.query.filter_by(email=request.form.get('email')).first():
            flash('Already Subscribed', 'subscribe')
        else:
            sub = Subscriber(email=request.form.get('email'))
            db.session.add(sub)
            db.session.commit()
            flash('Successfully Subcribed', 'subscribe')
    else:
        flash('Email field is required', 'subscribe')
    email = request.form.get('email')
    return redirect(request.referrer)


#Search Page Route
@user.route('/search')
def search():
    title = 'SacheFacts | Search'
    site = AccountSetting.query.get(1)
    if site is None:
        abort(500)
    featured = Post.query.filter_by(featured=True, status=True).all()
    blogs = []
    if request.args.get('q'):
        query = f'%{ request.args.get("q").strip() }%'
        blogs = Post.query.filter(Post.title.like(query)).all()
    print(blogs)
    return render_template('user/search.html', title=title, site=site, featured=featured, blogs=blogs)

App/templates/user/about.html
{% extends 'layouts/user.html' %}
{% block body %}
<div class="container"  id="searchdisplay">
    <div class="alert bg-dark rounded-0 font-monospace">
        <h2 class="font-weight-bold text-center text-white">About Us</h2>
    </div>
    <div class="m-5 text-center">
        Sache Facts Started in the spring of 2020. We have a vision to spread the knowledge about facts. Our goals is to provide you with the best realistic information around the world.
    </div>
    <div class="row">
        <div class="col-md-6 col-12 text-center">
            <img src="{{ url_for('static', filename=site.admin_photo) }}" alt="No Photo" title="Admin Photo" width="300px" height="300px">
        </div>
        <div class="col-md-6 col-12 text-center my-5">
            <p>Name : <span>{{ site.admin_displayname }}</span></p>
            <p>Contact : <span>{{ site.admin_contact }}</span></p>
            <p>Email : <span>{{ site.admin_email }}</span></p>
            <div class="icon mt-5 text-center">
                <a href="{{ site.site_youtube }}" target="_blank" class="mx-2" title="Youtube"><i class="fab fa-youtube fa-2x text-danger"></i></a>
                <a href="{{ site.site_facebook }}" target="_blank" class="mx-2" title="Facebook"><i class="fab fa-facebook fa-2x text-primary"></i></a>
                <a href="{{ site.site_instagram }}" target="_blank" class="mx-2" title="Instagram"><i class="fab fa-instagram fa-2x text-warning"></i></a>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

App/templates/user/blog.html
{% extends 'layouts/user.html' %}
{% block facebook %}
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v7.0" nonce="uJgzaG1L"></script>
{% endblock facebook %}
{% block body %}
<div class="card rounded-0 px-3 border-0" id="searchdisplay">
    <div class="card-header">
        <div class="text-center my-3">
            <h2 class="font-weight-bold ml-5">{{ blog.title }}</h2>
        </div>
    </div>
    <div class="card-body">
        <div class="my-2 d-flex justify-content-between">
            <span class="text-muted">Posted at : {{ blog.created_at }}</span>
            <span class="text-muted">Admin : {{ site.admin_displayname }}</span>
        </div>
        <hr>
        <div class="row">
            <div class="col-lg-9 col-md-8 col-12">
                <p class="font-weight-bold text-left">
                    Categories : &ensp;&ensp;&ensp;
                    {% for postcategory in postcategories %}{% if postcategory.post_id == blog.id %}{% for category in categories %}{% if postcategory.category_id == category.id  %}
                    <span class="badge bg-primary mx-1">{{ category.name }}</span>    
                    {% endif %}{% endfor %}{% endif %}{% endfor %}
                </p>
                <hr>
                {% if youtube %}
                <div>
                    <iframe width="100%" height="400px" src="{{ youtube }}"></iframe>
                </div>
                <hr>
                {% endif %}
                <div class="border rounded p-3">{{ blog.content|safe }}</div>
                <hr>
                <p class="font-weight-bold text-left">
                    Tags : &ensp;&ensp;&ensp;
                    {% for posttag in posttags %}{% if posttag.post_id == blog.id %}{% for tag in tags %}{% if posttag.tag_id == tag.id  %}
                    <span class="badge bg-primary mx-1">{{ tag.name }}</span>    
                    {% endif %}{% endfor %}{% endif %}{% endfor %}
                </p>
                <hr>
            </div>
            <div class="col-lg-3 col-md-4 col-12">
                <div class="img text-center">
                    <img src="{{ url_for('static', filename='post/'+blog.thumbnail) }}" class="img-thumbnail" alt="Post Thumbnail">
                </div>
                <hr>
                <p class="font-weight-bold">Youtube : <a class="font-weight-normal text-sm" href="{{ blog.youtube }}" target="_black">{{ blog.youtube }}</a></p>
                <p class="font-weight-bold">Facebook : <a class="font-weight-normal text-sm" href="{{ blog.facebook }}" target="_black">{{ blog.facebook }}</a></p>
                <p class="font-weight-bold">Instagram : <a class="font-weight-normal text-sm" href="{{ blog.instagram }}" target="_black">{{ blog.instagram }}</a></p>
                <p class="font-weight-bold">Link1 : <a class="font-weight-normal text-sm" href="{{ blog.link1 }}" target="_black">{{ blog.link1 }}</a></p>
                <p class="font-weight-bold">Link2 : <a class="font-weight-normal text-sm" href="{{ blog.link2 }}" target="_black">{{ blog.link2 }}</a></p>
            </div>
        </div>
    </div>
    <div class="card-footer d-flex justify-content-center">
        <div class="fb-comments" data-href="{{ url_for('users.singleblog', slag=blog.slag, _external=True) }}" data-numposts="5" data-width=""></div>
    </div>
</div>
{% endblock body %}

App/templates/user/blogs.html
{% extends 'layouts/user.html' %}
{% block css %}
{{ super() }}
<style>
    .blogthumbnail {
        background-repeat: no-repeat;
        background-size: 250px 250px;
        width: 250px;
        height: 250px;
    }

    .blogcontent {
        position: relative;
        -webkit-box-orient: vertical;
        display: -webkit-box;
        -webkit-line-clamp: 4;
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: normal;
    }

    .blogcontent p {
        margin-bottom: 0px;
    }
</style>
{% endblock css %}
{% block body %}
<div class="row">
    <div class="col-md-9 col-12">
        <div class="my-4" id="searchdisplay">
            {% for blog in blogs.items %}
            <div class="row">
                <div class="col-md-3 col-12 blogthumbnail" title="{{ blog.title }}" style="background-image: url({{ url_for('static', filename='post/'+blog.thumbnail) }});">
                    <p class="pt-2 pl-2">
                        {% for postcategory in postcategories %}{% if postcategory.post_id == blog.id %}{% for category in categories %}{% if postcategory.category_id == category.id  %}
                        <span class="badge bg-primary mx-1">{{ category.name }}</span>    
                        {% endif %}{% endfor %}{% endif %}{% endfor %}
                    </p>
                </div>
                <div class="col-md-9 col-12 card border-0">
                    <div class="card-header">
                        <div class="card-title">
                            <a class="h3 text-info text-decoration-none" href="{{ url_for('users.singleblog', slag=blog.slag) }}">{{ blog.title }}</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <div>
                                <p class="text-muted">Admin : {{ site.admin_displayname }}</p>
                            </div>
                            <div>
                                {% for posttag in posttags %}{% if posttag.post_id == blog.id %}{% for tag in tags %}{% if posttag.tag_id == tag.id  %}
                                <span class="badge bg-primary mx-1">{{ tag.name }}</span>
                                {% endif %}{% endfor %}{% endif %}{% endfor %}
                                <i class="fas fa-tags m-1 text-info"></i>
                            </div>
                        </div>
                        <div class="mt-2">
                            <span class="blogcontent">
                                {{ blog.content|safe }}
                            </span>
                            <span><a href="{{ url_for('users.singleblog', slag=blog.slag) }}"> read more...</a></span>
                            <p class="text-muted text-right">Posted at : {{ blog.created_at }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <hr class="my-4">
            {% endfor %}
        </div>
        <div class="d-flex justify-content-center">
            {% for page_num in blogs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)  %}
                {% if page_num %}
                    {% if blogs.page == page_num %}
                        <a class="btn btn-info mb-4 mr-1" href="{{ url_for('users.blogs', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-info mb-4 mr-1" href="{{ url_for('users.blogs', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="col-md-3 border-left px-3">
        {% include 'includes/_userSidebar.html' %}
    </div>
</div>
{% endblock body %}

App/templates/user/contact.html
{% extends 'layouts/user.html' %}
{% block body %}
<div class="container alert-secondary px-0"  id="searchdisplay">
    <div class="alert bg-dark font-monospace text-center mb-5 mx-0 rounded-0">
        <h2 class="text-white font-weight-bold">Contact Details</h2>
    </div>
    <div class="row mx-3">
        <div class="col-md-4 col-12">
            <div class="text-center">
                <p class="mb-0 text-decoration-underline font-weight-bold">Admin Name</p>
                <span>{{ site.admin_displayname }}</span>
                <hr class="mb-4 text-info">
            </div>
            <div class="text-center">
                <p class="mb-0 text-decoration-underline font-weight-bold">Contact No.</p>
                <a href="tel:{{ site.admin_contact }}" target="_blank" class="text-decoration-none text-dark">{{ site.admin_contact }}</a>
                <hr class="mb-4 text-info">
            </div>
            <div class="text-center">
                <p class="mb-0 text-decoration-underline font-weight-bold">Email Id</p>
                <a href="mailto:{{ site.admin_email }}" target="_blank" class="text-decoration-none text-dark">{{ site.admin_email }}</a>
                <hr class="mb-4 text-info">
            </div>
            <div class="text-center">
                <p class="mb-0 text-decoration-underline font-weight-bold">Youtube</p>
                <a href="{{ site.site_youtube }}" target="_blank" class="text-decoration-none text-dark">{{ site.site_youtube }}</a>
                <hr class="mb-4 text-info">
            </div>
            <div class="text-center">
                <p class="mb-0 text-decoration-underline font-weight-bold">Facebook</p>
                <a href="{{ site.site_facebook }}" target="_blank" class="text-decoration-none text-dark">{{ site.site_facebook }}</a>
                <hr class="mb-4 text-info">
            </div>
            <div class="text-center">
                <p class="mb-0 text-decoration-underline font-weight-bold">Instagram</p>
                <a href="{{ site.site_instagram }}" target="_blank" class="text-decoration-none text-dark">{{ site.site_instagram }}</a>
                <hr class="mb-4 text-info">
            </div>
        </div>
        <div class="col-md-8 col-12 px-3">
            <div class="card rounded-0 m-3">
                <div class="card-body alert-info">
                    <form action="{{ url_for('users.contact') }}" method="POST" novalidate>
                        {{ form.hidden_tag() }}
                        <div class="mb-3">
                            {{ form.fullname.label(class="form-label font-weight-bold") }}
                            {% if form.fullname.errors %} 
                            {{ form.fullname(class="form-control form-control-lg rounded-0 is-invalid") }}
                            <ul class="invalid-feedback">
                            {% for error in form.fullname.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                            {% else %} 
                            {{ form.fullname(class="form-control form-control-lg rounded-0")|safe }}
                            {% endif %} 
                        </div>
                        <div class="mb-3">
                            {{ form.email.label(class="form-label font-weight-bold") }}
                            {% if form.email.errors %} 
                            {{ form.email(class="form-control form-control-lg rounded-0 is-invalid") }}
                            <ul class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                            {% else %} 
                            {{ form.email(class="form-control form-control-lg rounded-0")|safe }}
                            {% endif %} 
                        </div>
                        <div class="mb-3">
                            {{ form.message.label(class="form-label font-weight-bold") }}
                            {% if form.message.errors %} 
                            {{ form.message(class="form-control form-control-lg rounded-0 is-invalid", rows=4) }}
                            <ul class="invalid-feedback">
                            {% for error in form.message.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                            {% else %} 
                            {{ form.message(class="form-control form-control-lg rounded-0", rows=4)|safe }}
                            {% endif %} 
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-12 mb-3">
                                {{ form.send(class="btn btn-info btn-lg rounded-0 px-5") }}
                            </div>
                            <div class="col-md-8 col-12 mb-3">
                                {% with messages = get_flashed_messages(category_filter=["contact"]) %}
                                    {% if messages %}
                                        {% for message in messages %}
                                        <p class="text-center my-2 text-danger"><strong>{{ message }}</strong></p>
                                        {% endfor %}
                                    {% endif %}
                                {% endwith %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

App/templates/user/home.html
{% extends 'layouts/user.html' %}

{% block mainContent %}
<div class="row">
    <div class="col-md-9 col-12">
        hii
    </div>
    <div class="col-md-3 border-left px-3">
        hello
    </div>
</div>
{% endblock mainContent %}

App/templates/user/search.html
{% extends 'layouts/user.html' %}
{% block css %}
{{ super() }}
<style>
    .blogcontent {
        position: relative;
        -webkit-box-orient: vertical;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: normal;
    }

    .blogcontent p {
        margin-bottom: 0px;
    }
</style>
{% endblock css %}
{% block body %}
<div class="row">
    <div class="col-md-9 col-12" id="searchdisplay">
    {% if blogs %}    
    {% for blog in blogs %}
        <div class="card my-2">
            <div class="card-header">
                <a href="{{ url_for('users.singleblog', slag=blog.slag) }}" class="text-decoration-none">
                    <div class="row">
                        <div class="col-3">
                            <img class="img-thumbnail" src="{{ url_for('static', filename='post/'+blog.thumbnail) }}" alt="No Thumbnail">
                        </div>
                        <div class="col-9">
                            <div class="title">
                                <p class="h3">{{ blog.title }}</p>
                                <hr>
                            </div>
                            <div class="d-flex justify-content-between">
                                <p class="text-muted">Posted at : {{ blog.created_at }}</p>
                                <p class="text-muted">Posted by : Admin</p>
                            </div>
                            <span class="blogcontent text-dark">
                                {{ blog.content|safe }}
                            </span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    {% endfor %}
    {% endif %}
    </div>
    <div class="col-md-3 border-left px-3">
        {% include 'includes/_userSidebar.html' %}
    </div>
</div>
{% endblock body %}